module LocalizationExecutor.LocalizerBase

open LocalizationExecutor.LocalizationCodeGen

let defaultLCtx: LGenCtx = {
    localeSwitch = "Locales.Provider.TextLocale.Value"
    objectType = "object"
    locales = ["null"; "Locales.JP"]
    lsclass = Some ("LText", "LString")
    methodToLsSuffix = Some "_ls"
    lsGenerated = []
    lskeyprefix = "$SET BY FILEINFO"
    errors = []
    renderFunc = "Render"
    funcStandardizer = fun s -> s.ToUpper()
    className = "LocalizedStrings"
    nestedClassName = "$NESTED CLASS WRITTEN BY FILE INFO"
    namespace_ = "$OVERWRITE NAMESPACE"
    outputHeader = """//----------------------
// <auto-generated>
//     Generated by Bagoum's Localization Utilities CSV Analysis.
//     Github project: https://github.com/Bagoum/localization-utils
// </auto-generated>
//----------------------

using System.Collections.Generic;
using BagoumLib.Culture;"""
}